---
apiVersion: v1
kind: Pod
metadata:
  name: utils-peer-pod
spec:
  restartPolicy: "Never"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  - name: composer-card-store
    persistentVolumeClaim:
      claimName: composer-pvc
  containers:
  - name: peer
    image: ibmblockchain/fabric-tools:1.0.3
    imagePullPolicy: Always
    command: ["sh", "-c", "sleep 100000" ]
    volumeMounts:
    - mountPath: /shared
      name: shared
    - mountPath: /home/composer/.composer
      name: composer-card-store
