---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-explorer
  labels:
    run: blockchain-explorer
spec:
  type: NodePort
  selector:
    name: blockchain-explorer
  ports:
  - protocol: TCP
    nodePort: 30880
    targetPort: 8080
    port: 8080
    name: blockchain-explorer